services:
  - type: web
    name: papelaria-backend
    env: docker
    plan: free
    branch: main
    region: oregon  # ou outra região disponível
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: SERVER_PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: "qa"
