-- Criação da tabela usuario
CREATE TABLE IF NOT EXISTS usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);


-- Criação da tabela estoque
CREATE TABLE IF NOT EXISTS estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_Produto INT NOT NULL UNIQUE,
    produto VARCHAR(100) NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    quantidade_Estoque INT NOT NULL
);


