[phases.setup]
commands = [
    "apt-get update",
    "apt-get install -y zip unzip curl",  # Adiciona zip explicitamente
    "curl -s https://get.sdkman.io | bash",
    "source ~/.sdkman/bin/sdkman-init.sh",
    "sdk install java 21"
]
