[phases.setup]
commands = [
    "curl -s https://get.sdkman.io | bash",
    "source ~/.sdkman/bin/sdkman-init.sh",
    "sdk install java 21"
]

[phases.build]
commands = ["./mvnw clean package -DskipTests"]
